# Generated by Django 2.1.7 on 2019-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='DateOfBirth',
            field=models.TextField(blank=True, default=-1990),
            preserve_default=False,
        ),
    ]
