# Generated by Django 2.1.7 on 2019-04-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190420_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='DateOfBirth',
            field=models.CharField(max_length=15),
        ),
    ]
