# Generated by Django 2.2 on 2019-05-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190429_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='data',
            name='Age',
            field=models.CharField(choices=[('0-19', 'Under 20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80'), ('80-90', 'Over 80')], default='Jon', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='LastName',
            field=models.CharField(default='Snow', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='ProcedureOutcome',
            field=models.CharField(choices=[('385669000', 'Successful'), ('385671000', 'Unsuccessful')], default='s', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='ProcedureReason',
            field=models.CharField(choices=[('247005', 'Brain damage'), ('2776000', 'Organic brain syndrome'), ('3119002', 'Brain stem laceration with open intracranial wound AND loss of consciousness'), ('4069002', 'Anoxic brain damage during AND/OR resulting from a procedure')], default='o', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='ProcedureType',
            field=models.CharField(choices=[('1868005', 'FB-Removal of Foreign Body from Brain')], default='idk', max_length=120),
            preserve_default=False,
        ),
    ]
