# Generated by Django 2.2 on 2019-05-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190508_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('ProcedureType', models.CharField(choices=[('1868005', 'FB-Removal of Foreign Body from Brain')], max_length=120)),
                ('ProcedureReason', models.CharField(choices=[('2470005', 'Brain damage'), ('2776000', 'Organic brain syndrome'), ('3119002', 'Brain stem laceration with open intracranial wound AND loss of consciousness'), ('4069002', 'Anoxic brain damage during AND/OR resulting from a procedure')], max_length=120)),
                ('ProcedureOutcome', models.CharField(choices=[('385669000', 'Successful'), ('385671000', 'Unsuccessful')], max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='ProcedureReason',
            field=models.CharField(choices=[('2470005', 'Brain damage'), ('2776000', 'Organic brain syndrome'), ('3119002', 'Brain stem laceration with open intracranial wound AND loss of consciousness'), ('4069002', 'Anoxic brain damage during AND/OR resulting from a procedure')], max_length=120),
        ),
    ]
